axis_linear: 1 # Left thumb stick vertical
scale_linear:  0.7 # 0.11
scale_linear_turbo: 1.5 # 0.22

axis_angular: 3  # Right thumb stick horizontal
scale_angular: 0.4 # 0.85

enable_button: 4 # Left trigger button
enable_turbo_button: 5 # Right trigger button


# axis_linear: 1  # Left thumb stick vertical
# scale_linear: 0.7
# scale_linear_turbo: 1.5

# axis_angular: 0  # Left thumb stick horizontal
# scale_angular: 0.4

# enable_button: 2  # Left trigger button
# enable_turbo_button: 5  # Right trigger button