axis_linear: 1
# scale_linear: 0.7
scale_linear: 0.5
scale_linear_turbo: 1.5

axis_angular: 0
# scale_angular: 0.4
scale_angular: 3.5

enable_button: 0  # L2 shoulder button
enable_turbo_button: 1  # L1 shoulder button
